# Generated by Django 5.2.12 on 2026-03-26 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_token', models.UUIDField(db_index=True, unique=True, verbose_name='QR token')),
                ('qr_token_hash', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='QR token hash')),
                ('default_visibility', models.CharField(choices=[('public', 'Public - Anyone'), ('medical', 'Medical Personnel Only'), ('private', 'Private - Owner Only')], default='public', max_length=20, verbose_name='default visibility')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('emergency_note', models.TextField(blank=True, verbose_name='emergency note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='last accessed at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'medical profile',
                'verbose_name_plural': 'medical profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
