# Generated by Django 5.2.12 on 2026-03-10 14:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public QR/NFC ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other / Prefer not to say')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('insurance_company', models.CharField(blank=True, max_length=120)),
                ('insurance_card_encrypted_path', models.CharField(blank=True, max_length=512, verbose_name='Encrypted Insurance Card Path')),
                ('chronic_diseases', models.TextField(blank=True, help_text="Comma-separated list, e.g. 'Diabetes Type 2, Hypertension'")),
                ('immune_diseases', models.TextField(blank=True, help_text='Immune / auto-immune conditions')),
                ('allergies', models.TextField(blank=True)),
                ('general_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Profile',
                'verbose_name_plural': 'Medical Profiles',
            },
        ),
        migrations.CreateModel(
            name='MedicalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Accident', 'Accident'), ('Fracture', 'Fracture'), ('Bleeding', 'Bleeding'), ('Surgery', 'Surgery'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('hospital', models.CharField(blank=True, max_length=150)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='Profiles.medicalprofile')),
            ],
            options={
                'verbose_name': 'Medical Event',
                'verbose_name_plural': 'Medical History',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dosage', models.CharField(blank=True, help_text="e.g. '500mg twice daily'", max_length=80)),
                ('start_date', models.DateField()),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='How many days the medication course lasts. Null = ongoing.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='Profiles.medicalprofile')),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('relationship', models.CharField(blank=True, max_length=60)),
                ('phone_number', models.CharField(max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='1 = primary contact, 2 = secondary contact')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='Profiles.medicalprofile')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'ordering': ['priority'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'priority'), name='unique_priority_per_profile')],
            },
        ),
    ]
