# Generated by Django 5.2.12 on 2026-03-11 10:41

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprofile',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for NFC/QR scanning', unique=True),
        ),
        migrations.AddIndex(
            model_name='medicalprofile',
            index=models.Index(fields=['user', 'updated_at'], name='profiles_me_user_id_962141_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalprofile',
            index=models.Index(fields=['public_id'], name='profiles_me_public__34990d_idx'),
        ),
    ]
