# Generated by Django 5.2.12 on 2026-03-11 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_medicalprofile_public_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='premium_access_logging',
            field=models.BooleanField(default=False, help_text='Track who views your profile. Requires premium subscription.', verbose_name='Access Log Tracking (Premium)'),
        ),
        migrations.CreateModel(
            name='ProfileAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_role', models.CharField(max_length=20)),
                ('access_type', models.CharField(choices=[('emergency', 'Emergency Scan'), ('api', 'API Access'), ('dashboard', 'Dashboard View')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_access_logs', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='profiles.medicalprofile')),
            ],
            options={
                'verbose_name': 'Profile Access Log',
                'verbose_name_plural': 'Profile Access Logs',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
