# Generated by Django 6.0.1 on 2026-03-05 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_alter_medicalprofile_medical_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprofile',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='Profiles.medicalprofile')),
            ],
        ),
    ]
