# Generated by Django 5.2.12 on 2026-03-11 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_medicalprofile_premium_access_logging_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='added_by_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_emergency_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Added by Doctor'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Contact is approved and visible', verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='pending_approval',
            field=models.BooleanField(default=False, help_text='Contact added by doctor, awaiting user approval', verbose_name='Pending User Approval'),
        ),
        migrations.AddField(
            model_name='medicalevent',
            name='added_by_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_medical_events', to=settings.AUTH_USER_MODEL, verbose_name='Added by Doctor'),
        ),
        migrations.AddField(
            model_name='medicalevent',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='medicalevent',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Event is approved and visible', verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='medicalevent',
            name='pending_approval',
            field=models.BooleanField(default=False, help_text='Event added by doctor, awaiting user approval', verbose_name='Pending User Approval'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='show_allergies_public',
            field=models.BooleanField(default=True, help_text='Everyone can see allergies in emergencies', verbose_name='Show Allergies to Public'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='show_blood_type_public',
            field=models.BooleanField(default=True, help_text='Everyone can see blood type in emergencies', verbose_name='Show Blood Type to Public'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='show_contacts_public',
            field=models.BooleanField(default=True, help_text='Anyone can view emergency contacts', verbose_name='Show Emergency Contacts to Public'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='show_history_public',
            field=models.BooleanField(default=False, help_text='Anyone can view medical history (doctors only by default)', verbose_name='Show Medical History to Public'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='show_medications_public',
            field=models.BooleanField(default=True, help_text='Anyone can view medications in emergencies', verbose_name='Show Medications to Public'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='show_physical_public',
            field=models.BooleanField(default=False, help_text='Anyone can view height/weight (doctors only by default)', verbose_name='Show Physical Info to Public'),
        ),
        migrations.AddField(
            model_name='medication',
            name='added_by_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_medications', to=settings.AUTH_USER_MODEL, verbose_name='Added by Doctor'),
        ),
        migrations.AddField(
            model_name='medication',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Medication is approved and visible', verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='medication',
            name='pending_approval',
            field=models.BooleanField(default=False, help_text='Medication added by doctor, awaiting user approval', verbose_name='Pending User Approval'),
        ),
    ]
