# Generated by Django 6.0.1 on 2026-03-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_alter_medicalprofile_medical_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprofile',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Accidents, fractures, old bleeding, etc.'),
        ),
    ]
