# Generated by Django 5.2.12 on 2026-03-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_emergencycontact_added_by_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(blank=True, help_text='Email for emergency notifications', max_length=254, verbose_name='Email Address'),
        ),
    ]
