# Generated by Django 5.2.12 on 2026-03-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_emergencycontact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileaccesslog',
            name='access_type',
            field=models.CharField(choices=[('emergency', 'Emergency Scan'), ('emergency_alert', 'Emergency Alert'), ('api', 'API Access'), ('dashboard', 'Dashboard View')], max_length=20),
        ),
    ]
