# Generated by Django 6.0.1 on 2026-03-07 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0005_medicalprofile_bracelet_id_alter_medicalprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprofile',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='Profiles.medicalprofile')),
            ],
        ),
    ]
