# Generated by Django 5.2.12 on 2026-03-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profileaccesslog_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='show_chronic_diseases_public',
            field=models.BooleanField(default=True, help_text='Everyone can see chronic diseases in emergencies', verbose_name='Show Chronic Diseases to Public'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='show_insurance_public',
            field=models.BooleanField(default=False, help_text='Anyone can view insurance info (doctors only by default)', verbose_name='Show Insurance to Public'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='show_notes_public',
            field=models.BooleanField(default=True, help_text='Everyone can see emergency notes in emergencies', verbose_name='Show Emergency Notes to Public'),
        ),
    ]
