# Generated by Django 5.2.12 on 2026-03-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_medicalprofile_show_chronic_diseases_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='is_active',
        ),
        migrations.AddField(
            model_name='medication',
            name='period_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days this medication should be taken. Leave empty for ongoing medications.', null=True, verbose_name='Treatment Duration (days)'),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='show_history_public',
            field=models.BooleanField(default=True, help_text='Anyone can view medical history (doctors only by default)', verbose_name='Show Medical History to Public'),
        ),
    ]
