# Generated by Django 5.2.12 on 2026-03-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_medication_is_active_medication_period_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='show_personal_public',
            field=models.BooleanField(default=True, help_text='Everyone can see personal details in emergencies', verbose_name='Show Personal Details to Public'),
        ),
    ]
