# Generated by Django 5.2.12 on 2026-03-12 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_carrier_order_tracking_number_bandreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='store_order_user_id_f28375_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='store_order_status_7b2658_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', 'status'], name='store_order_payment_35bfcd_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='store_order_order_n_317f52_idx'),
        ),
        migrations.AddIndex(
            model_name='syraband',
            index=models.Index(fields=['is_active', '-created_at'], name='store_syrab_is_acti_ebcc9e_idx'),
        ),
        migrations.AddIndex(
            model_name='syraband',
            index=models.Index(fields=['is_featured', 'is_active'], name='store_syrab_is_feat_77c482_idx'),
        ),
        migrations.AddIndex(
            model_name='syraband',
            index=models.Index(fields=['band_type', 'is_active'], name='store_syrab_band_ty_6a4321_idx'),
        ),
        migrations.AddIndex(
            model_name='syraband',
            index=models.Index(fields=['is_available', 'stock_quantity'], name='store_syrab_is_avai_211156_idx'),
        ),
    ]
