# Generated by Django 5.2.12 on 2026-03-12 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_emergencycontact_added_by_doctor_and_more'),
        ('store', '0003_order_store_order_user_id_f28375_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandregistration',
            name='medical_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='band_registrations', to='profiles.medicalprofile', verbose_name='Linked Medical Profile'),
        ),
    ]
