# Generated by Django 5.2.12 on 2026-03-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_bandregistration_medical_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syraband',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('red', 'Medical Red'), ('orange', 'Emergency Orange'), ('blue', 'Blue'), ('green', 'Green')], default='black', max_length=20),
        ),
        migrations.AlterField(
            model_name='syraband',
            name='material',
            field=models.CharField(choices=[('silicone', 'Medical Silicone'), ('stainless_steel', 'Stainless Steel')], default='silicone', max_length=20),
        ),
        migrations.AlterField(
            model_name='syraband',
            name='size',
            field=models.CharField(choices=[('adult', 'Adult'), ('kids', 'Kids')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='syrabandtype',
            name='name',
            field=models.CharField(choices=[('classic', 'Classic'), ('sport', 'Sport'), ('kids', 'Kids'), ('premium', 'Premium')], max_length=20, unique=True),
        ),
    ]
