# Generated by Django 5.2.12 on 2026-03-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_syraband_color_alter_syraband_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syraband',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xl', 'XL'), ('adult', 'Adult'), ('kids', 'Kids')], default='medium', max_length=20),
        ),
    ]
