# Generated by Django 5.2.12 on 2026-03-16 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_syraband_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='e.g., Home, Work', max_length=50)),
                ('name', models.CharField(help_text='Full name', max_length=200)),
                ('phone', models.CharField(help_text='Phone number', max_length=15)),
                ('address', models.TextField(help_text='Full address')),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, help_text='Neighborhood/Area', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Delivery notes')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Address',
                'verbose_name_plural': 'Saved Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
