# Generated by Django 5.2.12 on 2026-03-23 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_savedaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bandreview',
            index=models.Index(fields=['product', 'is_approved', '-created_at'], name='store_bandr_product_72cd9a_idx'),
        ),
        migrations.AddIndex(
            model_name='bandreview',
            index=models.Index(fields=['user', '-created_at'], name='store_bandr_user_id_a5c7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='bandreview',
            index=models.Index(fields=['is_approved', '-created_at'], name='store_bandr_is_appr_897261_idx'),
        ),
    ]
