# Generated by Django 5.2.12 on 2026-03-26 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hardware', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='product name')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='short description')),
                ('product_type', models.CharField(choices=[('bracelet', 'Bracelet'), ('accessory', 'Accessory'), ('bundle', 'Bundle')], default='bracelet', max_length=20, verbose_name='product type')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='category')),
                ('price', models.PositiveIntegerField(verbose_name='price in cents')),
                ('compare_at_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='compare at price')),
                ('cost_per_item', models.PositiveIntegerField(blank=True, null=True, verbose_name='cost per item')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('track_inventory', models.BooleanField(default=True, verbose_name='track inventory')),
                ('allow_oversell', models.BooleanField(default=False, verbose_name='allow oversell')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('out_of_stock', 'Out of Stock')], default='active', max_length=20, verbose_name='status')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='main image')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='additional images')),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Weight in grams', null=True, verbose_name='weight (g)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_email', models.EmailField(max_length=254, verbose_name='customer email')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='customer phone')),
                ('shipping_name', models.CharField(max_length=200, verbose_name='shipping name')),
                ('shipping_address', models.TextField(verbose_name='shipping address')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='shipping city')),
                ('shipping_postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('shipping_country', models.CharField(default='Egypt', max_length=50, verbose_name='country')),
                ('subtotal', models.PositiveIntegerField(verbose_name='subtotal')),
                ('shipping_cost', models.PositiveIntegerField(default=0, verbose_name='shipping cost')),
                ('tax', models.PositiveIntegerField(default=0, verbose_name='tax')),
                ('total', models.PositiveIntegerField(verbose_name='total')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash on Delivery'), ('card', 'Card Payment'), ('wallet', 'Digital Wallet')], default='cash', max_length=20, verbose_name='payment method')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='payment status')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='transaction ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('internal_notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='shipped at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='product name')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('price', models.PositiveIntegerField(verbose_name='price per unit')),
                ('total', models.PositiveIntegerField(verbose_name='total')),
                ('bracelet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='hardware.bracelet', verbose_name='bracelet')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
    ]
