# Generated by Django 5.2.12 on 2026-03-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syrauser',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Professional License Number'),
        ),
        migrations.AddField(
            model_name='syrauser',
            name='organization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Organization/Company'),
        ),
        migrations.AddField(
            model_name='syrauser',
            name='profile_role',
            field=models.CharField(choices=[('user', 'Regular User'), ('doctor', 'Doctor'), ('engineer', 'Engineer/Worker'), ('admin', 'Administrator')], default='user', max_length=20, verbose_name='Profile Access Role'),
        ),
        migrations.AddField(
            model_name='syrauser',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, verbose_name='Medical Specialty (for doctors)'),
        ),
        migrations.AddField(
            model_name='syrauser',
            name='store_role',
            field=models.CharField(choices=[('customer', 'Customer'), ('product_manager', 'Product Manager'), ('price_manager', 'Price Manager'), ('store_viewer', 'Store Viewer/Analyst'), ('store_admin', 'Store Administrator')], default='customer', max_length=20, verbose_name='Store Portal Role'),
        ),
    ]
