# Generated by Django 5.2.12 on 2026-03-11 10:41

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_syrauser_license_number_syrauser_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syrauser',
            name='national_id',
            field=models.CharField(db_index=True, help_text='14-digit Egyptian National ID', max_length=14, unique=True, validators=[accounts.models.validate_egyptian_national_id], verbose_name='Egyptian National ID'),
        ),
    ]
