# Generated by Django 5.2.12 on 2026-03-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_syrauser_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='syrauser',
            name='is_approved_doctor',
            field=models.BooleanField(default=False, help_text='Whether doctor account has been approved by admin', verbose_name='Doctor Account Approved'),
        ),
    ]
