# Generated by Django 5.2.12 on 2026-03-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_syrauser_is_approved_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='syrauser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='syrauser',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nationality'),
        ),
    ]
