# Generated by Django 5.2.12 on 2026-03-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_syrauser_gender_syrauser_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='syrauser',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, verbose_name='Email Verification Token'),
        ),
        migrations.AddField(
            model_name='syrauser',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Whether user has verified their email address', verbose_name='Email Verified'),
        ),
        migrations.AddField(
            model_name='syrauser',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text='Whether user has verified their phone number', verbose_name='Phone Verified'),
        ),
        migrations.AddField(
            model_name='syrauser',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_licenses/', verbose_name='Medical License Image'),
        ),
        migrations.AddField(
            model_name='syrauser',
            name='phone_otp',
            field=models.CharField(blank=True, max_length=6, verbose_name='Phone OTP'),
        ),
        migrations.AddField(
            model_name='syrauser',
            name='phone_otp_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phone OTP Expiry'),
        ),
    ]
