# Generated by Django 5.2.12 on 2026-03-26 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='allergen name')),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life Threatening')], default='moderate', max_length=20, verbose_name='severity')),
                ('visibility', models.CharField(choices=[('public', 'Public - Anyone'), ('medical', 'Medical Personnel Only'), ('private', 'Private - Owner Only')], default='public', max_length=20, verbose_name='visibility')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='profiles.medicalprofile', verbose_name='medical profile')),
            ],
            options={
                'verbose_name': 'allergy',
                'verbose_name_plural': 'allergies',
                'ordering': ['-severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='condition name')),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life Threatening')], default='moderate', max_length=20, verbose_name='severity')),
                ('visibility', models.CharField(choices=[('public', 'Public - Anyone'), ('medical', 'Medical Personnel Only'), ('private', 'Private - Owner Only')], default='public', max_length=20, verbose_name='visibility')),
                ('diagnosed_date', models.DateField(blank=True, null=True, verbose_name='diagnosed date')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='profiles.medicalprofile', verbose_name='medical profile')),
            ],
            options={
                'verbose_name': 'condition',
                'verbose_name_plural': 'conditions',
                'ordering': ['-severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='contact name')),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('other', 'Other')], default='other', max_length=20, verbose_name='relationship')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary contact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='profiles.medicalprofile', verbose_name='medical profile')),
            ],
            options={
                'verbose_name': 'emergency contact',
                'verbose_name_plural': 'emergency contacts',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='medication name')),
                ('dosage', models.CharField(max_length=100, verbose_name='dosage')),
                ('frequency', models.CharField(choices=[('once', 'Once daily'), ('twice', 'Twice daily'), ('three_times', 'Three times daily'), ('daily', 'Once daily'), ('weekly', 'Weekly'), ('as_needed', 'As needed')], default='daily', max_length=20, verbose_name='frequency')),
                ('visibility', models.CharField(choices=[('public', 'Public - Anyone'), ('medical', 'Medical Personnel Only'), ('private', 'Private - Owner Only')], default='public', max_length=20, verbose_name='visibility')),
                ('prescribed_by', models.CharField(blank=True, max_length=200, verbose_name='prescribed by')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='reason for taking')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='profiles.medicalprofile', verbose_name='medical profile')),
            ],
            options={
                'verbose_name': 'medication',
                'verbose_name_plural': 'medications',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
