# Generated by Django 5.2.12 on 2026-03-26 19:59

import apps.common.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracelet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(db_index=True, max_length=50, unique=True, validators=[apps.common.validators.validate_serial_number], verbose_name='serial number')),
                ('qr_token', models.UUIDField(db_index=True, unique=True, verbose_name='QR token')),
                ('claim_pin', models.CharField(max_length=6, validators=[apps.common.validators.validate_claim_pin], verbose_name='claim PIN')),
                ('status', models.CharField(choices=[('unclaimed', 'Unclaimed'), ('claimed', 'Claimed'), ('active', 'Active'), ('lost', 'Lost'), ('suspended', 'Suspended')], default='unclaimed', max_length=20, verbose_name='status')),
                ('ordered_at', models.DateTimeField(blank=True, null=True, verbose_name='ordered at')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='shipped at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='claimed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracelets', to='profiles.medicalprofile', verbose_name='medical profile')),
            ],
            options={
                'verbose_name': 'bracelet',
                'verbose_name_plural': 'bracelets',
                'ordering': ['-created_at'],
            },
        ),
    ]
